#!/bin/sh
# /etc/init.d/teamcity -  startup script for teamcity

#DEFINE EXPORTS

case $1 in
  start)
    echo "TeamCity starts..."
    start-stop-daemon --start  -c teamcity --exec ${TEAMCITY_BIN_PATH}/bin/teamcity-server.sh start
    echo "TeamCity started"
    ;;
  stop)
    echo "TeamCity stops..."
    start-stop-daemon --start -c teamcity  --exec ${TEAMCITY_BIN_PATH}/bin/teamcity-server.sh stop
    echo "TeamCity stopped"
    ;;
  restart)
    echo "TeamCity restarts..."
    start-stop-daemon --start  -c teamcity --exec ${TEAMCITY_BIN_PATH}/bin/teamcity-server.sh stop
    start-stop-daemon --start  -c teamcity --exec ${TEAMCITY_BIN_PATH}/bin/teamcity-server.sh start
    echo "TeamCity restarted"
    ;;
  *)
    echo "Usage: /etc/init.d/teamcity {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
